=== RJNewbyte/Tarea-10---XSD/enunciado_tarea_xsd/a25_factura.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="factura">
        <xs:complexType>
            <xs:all>
                <xs:element name="datosEmisor" type="emisor"></xs:element>
                <xs:element name="datosCliente" type="cliente"></xs:element>
                <xs:element name="detalleFactura" type="factura"></xs:element>
            </xs:all>
            <xs:attribute name="número" type="xs:positiveInteger" use="required"></xs:attribute>
            <xs:attribute name="fecha" type="xs:date" use="required"></xs:attribute>
            <xs:attribute name="moneda" fixed="Euro"></xs:attribute>
        </xs:complexType>
    </xs:element>

    <xs:simpleType name="tipoTexto">
        <xs:restriction base="xs:string">
            <xs:minLength value="5"></xs:minLength>
            <xs:maxLength value="20"></xs:maxLength>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="cif">
        <xs:restriction base="xs:string">
            <xs:pattern value="\d{8}-[A-Z]"></xs:pattern>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="telefono">
        <xs:restriction base="xs:string">
            <xs:pattern value="\d{9}"></xs:pattern>
        </xs:restriction>
    </xs:simpleType>

    <xs:group name="grupoPersona">
        <xs:sequence>
            <xs:element name="nombre" type="tipoTexto"></xs:element>
            <xs:element name="cif" type="cif"></xs:element>
            <xs:element name="teléfono" type="telefono"></xs:element>
        </xs:sequence>
    </xs:group>

    <xs:complexType name="emisor">
        <xs:group ref="grupoPersona"></xs:group>
    </xs:complexType>

    <xs:complexType name="cliente">
        <xs:group ref="grupoPersona"></xs:group>
    </xs:complexType>

    <xs:complexType name="factura">
        <xs:sequence>
            <xs:element name="línea" maxOccurs="15">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="descripción"></xs:element>
                        <xs:element name="cantidad" type="xs:positiveInteger"></xs:element>
                        <xs:element name="oferta" minOccurs="0"/>
                        <xs:element name="pvp" type="tipoPrecio"></xs:element>
                    </xs:sequence>
                    <xs:attribute name="código-artículo" type="xs:ID" use="required"></xs:attribute>
                    <xs:attribute name="tipo" type="tipoArtículo" use="optional">
                    </xs:attribute>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
        <xs:attribute name="importe" type="tipoPrecio" use="required"></xs:attribute>
    </xs:complexType>

    <xs:simpleType name="tipoPrecio">
        <xs:restriction base="xs:decimal">
            <xs:minExclusive value="0"></xs:minExclusive>
            <xs:maxInclusive value="999"></xs:maxInclusive>
            <xs:totalDigits value="5"></xs:totalDigits>
            <xs:fractionDigits value="2"></xs:fractionDigits>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="tipoArtículo">
        <xs:restriction base="xs:string">
            <xs:enumeration value="Libro"></xs:enumeration>
            <xs:enumeration value="DVD"></xs:enumeration>
            <xs:enumeration value="Varios"></xs:enumeration>
        </xs:restriction>
    </xs:simpleType>

</xs:schema>

=== RJNewbyte/Tarea-10---XSD/enunciado_tarea_xsd/a25_factura.xml
<?xml version="1.0" encoding="UTF-8"?>
<factura xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:noNamespaceSchemaLocation="a25_factura.xsd"
  número="27" fecha="2013-12-18" moneda="Euro">
  <datosEmisor>
    <nombre>Librería García</nombre>
    <cif>44555666-B</cif>
    <teléfono>777888999</teléfono>
  </datosEmisor>
  <datosCliente>
    <nombre>Biblioteca Txantrea</nombre>
    <cif>33111222-A</cif>
    <teléfono>333999444</teléfono>
  </datosCliente>
  <detalleFactura importe="86.12">
    <línea código-artículo="AW7" tipo="Libro">
      <descripción>Analítica Web 2.0</descripción>
      <cantidad>1</cantidad>
      <oferta />
      <pvp>25.12</pvp>
    </línea>
    <línea código-artículo="CP5" tipo="DVD">
      <descripción>Curso de HTML</descripción>
      <cantidad>2</cantidad>
      <pvp>30.5</pvp>
    </línea>
  </detalleFactura>
</factura>
