=== RJNewbyte/Tarea-10---XSD/enunciado_tarea_xsd/a26_registroConexiones.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="registro">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="usuario" type="tipoPersona" minOccurs="0" maxOccurs="unbounded"></xs:element>
                <xs:element name="empleado" type="tipoPersonaAmpliado" minOccurs="0"
                    maxOccurs="unbounded"></xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="tipoPersona">
        <xs:sequence>
            <xs:element name="apellidosYNombre" minOccurs="0">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:pattern value="[a-zA-Z\s]{1,30},[a-zA-Z\s]{1,20}"></xs:pattern>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="email" minOccurs="0">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:pattern value="[a-z]{1,15}@[a-z]{1,25}.[a-z]{2,4}"></xs:pattern>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="conexiones" type="conexiones" minOccurs="0" maxOccurs="unbounded"></xs:element>
        </xs:sequence>
        <xs:attribute name="identificador" type="validaID"></xs:attribute>
    </xs:complexType>

    <xs:complexType name="tipoPersonaAmpliado">
        <xs:complexContent>
            <xs:extension base="tipoPersona">
                <xs:sequence>
                    <xs:element name="departamento">
                        <xs:complexType>
                            <xs:choice>
                                <xs:element name="administración"></xs:element>
                                <xs:element name="informática"></xs:element>
                                <xs:element name="marketing"></xs:element>
                            </xs:choice>
                        </xs:complexType>
                    </xs:element>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:simpleType name="validaID">
        <xs:restriction base="xs:string">
            <xs:pattern value="[UO]\d{1,5}"></xs:pattern>
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="conexiones">
        <xs:sequence>
            <xs:element name="conexión" minOccurs="0" maxOccurs="unbounded">
                <xs:complexType>
                    <xs:simpleContent>
                        <xs:extension base="xs:positiveInteger">
                            <xs:attribute name="fecha" type="xs:date"></xs:attribute>
                            <xs:attribute name="hora" type="xs:time"></xs:attribute>
                        </xs:extension>
                    </xs:simpleContent>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>

</xs:schema>

=== RJNewbyte/Tarea-10---XSD/enunciado_tarea_xsd/a26_registroConexiones.xml
<?xml version="1.0" encoding="UTF-8"?>
<registro xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:noNamespaceSchemaLocation="a26_registroConexiones.xsd">
  <usuario identificador="U123">
    <apellidosYNombre>Sanz Tapia,Ana</apellidosYNombre>
    <email>asanz@jmail.com</email>
    <conexiones>
      <conexión fecha="2014-02-23" hora="19:15:40">122</conexión>
      <conexión fecha="2014-02-23" hora="20:30:22">617</conexión>
      <conexión fecha="2014-02-24" hora="11:18:31">25</conexión>
    </conexiones>
  </usuario>
  <usuario identificador="U96">
    <apellidosYNombre>Ruiz Hierro,Pedro</apellidosYNombre>
    <email>pruiz@jotmail.com</email>
    <conexiones>
      <conexión fecha="2014-02-25" hora="20:33:55">390</conexión>
    </conexiones>
  </usuario>
  <empleado identificador="O4">
    <apellidosYNombre>Vera Gil,Marta</apellidosYNombre>
    <email>mvera@yajoo.es</email>
    <conexiones />
    <departamento>
      <marketing />
    </departamento>
  </empleado>
</registro>
